### PR TITLE
Update implementation from interfaces

### LINKED ISSUE #12: Broken compatibility in StreamFactory with latest http-interop/http-factory update
I create a fork fixing this issues, but i don't know if new methods are well implemented or not, If you want i can make a pull request for review.

I need this fix to continue developing my current personal project.

Sorry for my english level.

Greetings

### PR DESCRIPTION
**Pull request by shadowhand**
Stream and server factory have been updated in v0.2.0.

Fixes #12

### CODE REVIEW

**Comment by shadowhand** [comment]
Build will continue to fail until tests are updated.

**Comment by shadowhand** [comment]
@ajgarlag HHVM is now failing because of the globals tests you added.

**Comment by ajgarlag** [comment]
It worked at #14, I'll review it.

**Comment by ajgarlag** [comment]
@shadowhand The problem is not that the tests are failing in HHVM, but that they should be failing with any PHP version.

After reviewing travis-ci logs, I've noticed that the HHVM build is the only one that updates the http-interop/http-factory-tests revision, so it is the only one that fails. You need to relaunch build jobs for every PHP version to test them against the updated tests.

To fix the tests in http-factory-diactoros, the commit a2f36bba69bf69dad9c931ff8211cb24bd51994e is needed.

**Comment by shadowhand** [comment]
@ajgarlag thanks! There were still some warnings about globals, might want to check it out https://travis-ci.org/http-interop/http-factory-diactoros/jobs/179447209

Tagged in 0.1.0

**Pull request merged**
